<?php

namespace Database\Seeders;

use App\Models\archivo\ArchivoSeccion;
use App\Models\archivo\ArchivoSerie;
use Illuminate\Database\Seeder;

class SeccionesSeeder extends Seeder
{
    public function run()
    {
//        ArchivoSeccion::create([ 'clave' => '1S', 'nombre' => 'Infraestructura publica'  ])->series()->saveMany([
//            new ArchivoSerie(['clave' => '1', 'nombre' => 'Licencias y permisos de uso de suelo' ]),
//            new ArchivoSerie(['clave' => '2', 'nombre' => 'Licencias y permisos para la construcción, ampliación o remodelación de casas edificios, etc.' ]),
//            new ArchivoSerie(['clave' => '3', 'nombre' => 'Conexiones de drenaje, agua, etc.' ]),
//            new ArchivoSerie(['clave' => '4', 'nombre' => 'Avalúos' ]),
//            new ArchivoSerie(['clave' => '5', 'nombre' => 'Constancias de alineamiento y números oficiales' ]),
//            new ArchivoSerie(['clave' => '6', 'nombre' => 'Reservas Territoriales' ]),
//            new ArchivoSerie(['clave' => '7', 'nombre' => 'Fraccionamientos' ]),
//            new ArchivoSerie(['clave' => '8', 'nombre' => 'Licencias y Regulación de la tenencia de la tierra' ]),
//            new ArchivoSerie(['clave' => '9', 'nombre' => 'Padrón Catastral' ]),
//        ]);

        ArchivoSeccion::create([ 'clave' => '1S', 'nombre' => 'Proceso de Junta De Gobierno'  ])->series()->saveMany([
            new ArchivoSerie(['clave' => '1', 'nombre' => 'Sesión Ordinaria' ]),
            new ArchivoSerie(['clave' => '2', 'nombre' => 'Sesión Extraordinaria' ]),
        ]);

//        ArchivoSeccion::create([ 'clave' => '2S', 'nombre' => 'Planeación y urbanización'  ])->series()->saveMany([
//            new ArchivoSerie(['clave' => '1', 'nombre' => 'Planes y programas de urbanismo y desarrollo municipal' ]),
//            new ArchivoSerie(['clave' => '2', 'nombre' => 'Programas Sectoriales' ]),
//            new ArchivoSerie(['clave' => '3', 'nombre' => 'Desarrollo Urbano y Regional' ]),
//            new ArchivoSerie(['clave' => '4', 'nombre' => 'Asentamientos Humanos' ]),
//            new ArchivoSerie(['clave' => '5', 'nombre' => 'Desarrollo Agropecuario' ]),
//            new ArchivoSerie(['clave' => '6', 'nombre' => 'Desarrollo Económico' ]),
//        ]);

        ArchivoSeccion::create([ 'clave' => '2S', 'nombre' => 'Conciliación Laboral en Conflictos del Orden Local'  ])->series()->saveMany([
            new ArchivoSerie(['clave' => '1', 'nombre' => 'Procedimiento de Conciliación Prejudicial' ]),
            new ArchivoSerie(['clave' => '2', 'nombre' => 'Reclutamiento y Selección de Conciliadores' ]),
            new ArchivoSerie(['clave' => '3', 'nombre' => 'Orientación en Materia de Conciliación Laboral' ]),
            new ArchivoSerie(['clave' => '4', 'nombre' => 'Asesorías Especializadas en Materia de Conciliación Laboral' ]),
            new ArchivoSerie(['clave' => '5', 'nombre' => 'Notificación de Audiencias de Conciliación' ]),
        ]);

        ArchivoSeccion::create([ 'clave' => '3S', 'nombre' => 'Asistencia social'  ])->series()->saveMany([
            new ArchivoSerie(['clave' => '1', 'nombre' => 'Programas de asistencia Social' ]),
            new ArchivoSerie(['clave' => '2', 'nombre' => 'Apoyos y Estrategias' ]),
            new ArchivoSerie(['clave' => '3', 'nombre' => 'Asistencia Médica' ]),
        ]);
        ArchivoSeccion::create([ 'clave' => '4S', 'nombre' => 'Junta de reclutamiento'  ])->series()->saveMany([
            new ArchivoSerie(['clave' => '1', 'nombre' => 'Sorteos' ]),
            new ArchivoSerie(['clave' => '2', 'nombre' => 'Cartillas' ]),
            new ArchivoSerie(['clave' => '3', 'nombre' => 'Informe del Reclutamiento' ]),
        ]);
        ArchivoSeccion::create([ 'clave' => '5S', 'nombre' => 'Registro del estado familiar'  ])->series()->saveMany([
            new ArchivoSerie(['clave' => '1', 'nombre' => 'Actas' ]),
            new ArchivoSerie(['clave' => '2', 'nombre' => 'Registros' ]),
            new ArchivoSerie(['clave' => '3', 'nombre' => 'Estadísticas' ]),
            new ArchivoSerie(['clave' => '4', 'nombre' => 'Juicios' ]),
        ]);
        ArchivoSeccion::create([ 'clave' => '6S', 'nombre' => 'Educación, cultura, y fomento deportivo'  ])->series()->saveMany([
            new ArchivoSerie(['clave' => '1', 'nombre' => 'Actos cívicos tradicionales' ]),
            new ArchivoSerie(['clave' => '2', 'nombre' => 'Eventos o Actividades Cívicas' ]),
            new ArchivoSerie(['clave' => '3', 'nombre' => 'Estímulos a la Educación' ]),
            new ArchivoSerie(['clave' => '4', 'nombre' => 'Promoción del deporte' ]),
            new ArchivoSerie(['clave' => '5', 'nombre' => 'Casa de la Cultura' ]),
        ]);
        ArchivoSeccion::create([ 'clave' => '7S', 'nombre' => 'Protección, conservación, y restauración del medio ambiente'  ])->series()->saveMany([
            new ArchivoSerie(['clave' => '1', 'nombre' => 'Reservas Ecológicas' ]),
            new ArchivoSerie(['clave' => '2', 'nombre' => 'Programas y Campañas en materia del Medio Ambiente' ]),
            new ArchivoSerie(['clave' => '3', 'nombre' => 'Reforestación' ]),
            new ArchivoSerie(['clave' => '4', 'nombre' => 'Licencias y Permisos en Materia Ecológica' ]),
            new ArchivoSerie(['clave' => '5', 'nombre' => 'Calles Parques y Jardines (mantenimiento y equipamiento)' ]),
            new ArchivoSerie(['clave' => '6', 'nombre' => 'Prevención, y Conservación del Medio Ambiente' ]),
            new ArchivoSerie(['clave' => '7', 'nombre' => 'Residuos Sólidos' ]),
            new ArchivoSerie(['clave' => '8', 'nombre' => 'Relleno Sanitario' ]),
        ]);
        ArchivoSeccion::create([ 'clave' => '8S', 'nombre' => 'Turismo y recreación'  ])->series()->saveMany([
            new ArchivoSerie(['clave' => '1', 'nombre' => 'Programas y Proyectos Turísticos' ]),
            new ArchivoSerie(['clave' => '2', 'nombre' => 'Desarrollo de Proyectos Turísticos' ]),
            new ArchivoSerie(['clave' => '3', 'nombre' => 'Parques' ]),
            new ArchivoSerie(['clave' => '4', 'nombre' => 'Zonas Arqueológicas' ]),
            new ArchivoSerie(['clave' => '5', 'nombre' => 'Deportivos' ]),
        ]);
        ArchivoSeccion::create([ 'clave' => '9S', 'nombre' => 'Comercios, mercados, tianguis y ferias'  ])->series()->saveMany([
            new ArchivoSerie(['clave' => '1', 'nombre' => 'Licencias y permisos Comerciales' ]),
            new ArchivoSerie(['clave' => '2', 'nombre' => 'Convenios y Asociaciones' ]),
            new ArchivoSerie(['clave' => '3', 'nombre' => 'Supervisiones' ]),
            new ArchivoSerie(['clave' => '4', 'nombre' => 'Notificaciones' ]),
            new ArchivoSerie(['clave' => '5', 'nombre' => 'Inconformidades y Quejas' ]),
        ]);
        ArchivoSeccion::create([ 'clave' => '10S', 'nombre' => 'Servicios públicos municipales'  ])->series()->saveMany([
            new ArchivoSerie(['clave' => '1', 'nombre' => 'Agua potable, drenaje, alcantarillado, tratamiento y disposición de aguas residuales' ]),
            new ArchivoSerie(['clave' => '2', 'nombre' => 'Alumbrado Público' ]),
            new ArchivoSerie(['clave' => '3', 'nombre' => 'Limpia, Recolección, traslado, tratamiento y disposición final de residuos' ]),
            new ArchivoSerie(['clave' => '4', 'nombre' => 'Panteones' ]),
            new ArchivoSerie(['clave' => '5', 'nombre' => 'Rastro' ]),
            new ArchivoSerie(['clave' => '6', 'nombre' => 'Sanidad Municipal' ]),
            new ArchivoSerie(['clave' => '7', 'nombre' => 'Concesiones de Servicios' ]),
            new ArchivoSerie(['clave' => '8', 'nombre' => 'Conservación de Obras de Interés Social' ]),
        ]);
        ArchivoSeccion::create([ 'clave' => '11S', 'nombre' => 'Seguridad Pública y conciliación municipal'  ])->series()->saveMany([
            new ArchivoSerie(['clave' => '1', 'nombre' => 'Programas y Proyectos en materia de seguridad' ]),
            new ArchivoSerie(['clave' => '2', 'nombre' => 'Apoyos en seguridad Pública' ]),
            new ArchivoSerie(['clave' => '3', 'nombre' => 'Operativos' ]),
            new ArchivoSerie(['clave' => '4', 'nombre' => 'Parte Informativo' ]),
            new ArchivoSerie(['clave' => '5', 'nombre' => 'Convenios de Coordinación de Seguridad Pública' ]),
            new ArchivoSerie(['clave' => '6', 'nombre' => 'Amonestaciones y multas' ]),
            new ArchivoSerie(['clave' => '7', 'nombre' => 'Arrestos Administrativos' ]),
            new ArchivoSerie(['clave' => '8', 'nombre' => 'Puesta a disposición' ]),
            new ArchivoSerie(['clave' => '9', 'nombre' => 'Suspensiones de Obras o Actividades' ]),
            new ArchivoSerie(['clave' => '10', 'nombre' => 'Cancelación de Permisos y Obras' ]),
            new ArchivoSerie(['clave' => '11', 'nombre' => 'Clausuras' ]),
            new ArchivoSerie(['clave' => '12', 'nombre' => 'Equipamiento y Desarrollo Organizacional' ]),
            new ArchivoSerie(['clave' => '13', 'nombre' => 'Resguardo de Equipo y Material' ]),
        ]);
        ArchivoSeccion::create([ 'clave' => '12S', 'nombre' => 'Protección civil'  ])->series()->saveMany([
            new ArchivoSerie(['clave' => '1', 'nombre' => 'Apoyos (simulacros, pláticas, etc.)' ]),
            new ArchivoSerie(['clave' => '2', 'nombre' => 'Inspecciones' ]),
            new ArchivoSerie(['clave' => '3', 'nombre' => 'Capacitación' ]),
            new ArchivoSerie(['clave' => '4', 'nombre' => 'Supervisiones' ]),
        ]);
        ArchivoSeccion::create([ 'clave' => '1C', 'nombre' => 'Legislación'  ])->series()->saveMany([
            new ArchivoSerie(['clave' => '1', 'nombre' => 'Disposiciones legales en la materia' ]),
            new ArchivoSerie(['clave' => '2', 'nombre' => 'Programas y proyectos sobre legislación' ]),
            new ArchivoSerie(['clave' => '3', 'nombre' => 'Leyes' ]),
            new ArchivoSerie(['clave' => '4', 'nombre' => 'Códigos' ]),
            new ArchivoSerie(['clave' => '5', 'nombre' => 'Convenios y Tratados Internacionales' ]),
            new ArchivoSerie(['clave' => '6', 'nombre' => 'Decretos' ]),
            new ArchivoSerie(['clave' => '7', 'nombre' => 'Reglamentos' ]),
            new ArchivoSerie(['clave' => '8', 'nombre' => 'Acuerdos generales' ]),
            new ArchivoSerie(['clave' => '9', 'nombre' => 'Circulares' ]),
            new ArchivoSerie(['clave' => '10', 'nombre' => 'Instrumentos Jurídicos Consensuales (convenios, bases de colaboración, acuerdos, etc.)' ]),
            new ArchivoSerie(['clave' => '11', 'nombre' => 'Resoluciones' ]),
            new ArchivoSerie(['clave' => '12', 'nombre' => 'Compilaciones jurídicas' ]),
            new ArchivoSerie(['clave' => '13', 'nombre' => 'Periódico Oficial del Estado (publicaciones en el)' ]),
            new ArchivoSerie(['clave' => '14', 'nombre' => 'Normas Oficiales Mexicanas' ]),
            new ArchivoSerie(['clave' => '15', 'nombre' => 'Comités y subcomités de normalización' ]),
            new ArchivoSerie(['clave' => '16', 'nombre' => 'Representaciones de la Secretaría ante los Órganos de Gobierno' ]),
            new ArchivoSerie(['clave' => '16.1', 'nombre' => 'Información derivada de las representaciones de la Secretaría ante los órganos de Gobierno.' ]),
            new ArchivoSerie(['clave' => '16.2', 'nombre' => 'Actas y Acuerdos de las representaciones de la Secretaría ante los órganos de Gobierno.' ]),

        ]);
        ArchivoSeccion::create([ 'clave' => '2C', 'nombre' => 'Asuntos jurídicos'  ])->series()->saveMany([
            new ArchivoSerie(['clave' => '1', 'nombre' => 'Disposiciones jurídicas en la materia' ]),
            new ArchivoSerie(['clave' => '2', 'nombre' => 'Programas y proyectos en la materia' ]),
            new ArchivoSerie(['clave' => '3', 'nombre' => 'Registro y certificación de firmas' ]),
            new ArchivoSerie(['clave' => '4', 'nombre' => 'Registro y certificación de firmas acreditadas ante la dependencia' ]),
            new ArchivoSerie(['clave' => '5', 'nombre' => 'Actuaciones y representaciones en materia legal' ]),
            new ArchivoSerie(['clave' => '6', 'nombre' => 'Asistencia, consulta y asesorías' ]),
            new ArchivoSerie(['clave' => '7', 'nombre' => 'Estudios, dictámenes e informes' ]),
            new ArchivoSerie(['clave' => '8', 'nombre' => 'Juicios contra la dependencia' ]),
            new ArchivoSerie(['clave' => '9', 'nombre' => 'Juicios de la dependencia' ]),
            new ArchivoSerie(['clave' => '10', 'nombre' => 'Amparos' ]),
            new ArchivoSerie(['clave' => '11', 'nombre' => 'Interposición de recursos administrativos' ]),
            new ArchivoSerie(['clave' => '12', 'nombre' => 'Opiniones técnico jurídicas' ]),
            new ArchivoSerie(['clave' => '13', 'nombre' => 'Inspección y designación de peritos' ]),
            new ArchivoSerie(['clave' => '14', 'nombre' => 'Desfalcos, peculados, fraudes y cohechos' ]),
            new ArchivoSerie(['clave' => '15', 'nombre' => 'Notificaciones' ]),
            new ArchivoSerie(['clave' => '16', 'nombre' => 'Inconformidades y peticiones' ]),
            new ArchivoSerie(['clave' => '17', 'nombre' => 'Delitos y fallas' ]),
            new ArchivoSerie(['clave' => '18', 'nombre' => 'Derechos Humanos' ]),

        ]);
        ArchivoSeccion::create([ 'clave' => '3C', 'nombre' => 'Programación, organización y presupuestación'  ])->series()->saveMany([
            new ArchivoSerie(['clave' => '1', 'nombre' => 'Disposiciones en materia de programación' ]),
            new ArchivoSerie(['clave' => '2', 'nombre' => 'Programas y proyectos en materia de programación' ]),
            new ArchivoSerie(['clave' => '3', 'nombre' => 'Procesos de programación' ]),
            new ArchivoSerie(['clave' => '4', 'nombre' => 'Programa anual de inversiones' ]),
            new ArchivoSerie(['clave' => '5', 'nombre' => 'Registro programático de proyectos institucionales' ]),
            new ArchivoSerie(['clave' => '6', 'nombre' => 'Registro programático de proyectos especiales' ]),
            new ArchivoSerie(['clave' => '7', 'nombre' => 'Programas operativos anuales' ]),
            new ArchivoSerie(['clave' => '8', 'nombre' => 'Disposiciones en materia de organización' ]),
            new ArchivoSerie(['clave' => '9', 'nombre' => 'Programas y proyectos en materia de organización' ]),
            new ArchivoSerie(['clave' => '10', 'nombre' => 'Dictamen técnico de estructuras' ]),
            new ArchivoSerie(['clave' => '11', 'nombre' => 'Integración y dictamen de manuales de organización' ]),
            new ArchivoSerie(['clave' => '12', 'nombre' => 'Normas y lineamientos de procesos / procedimientos' ]),
            new ArchivoSerie(['clave' => '13', 'nombre' => 'Acciones de Modernización administrativa' ]),
            new ArchivoSerie(['clave' => '14', 'nombre' => 'Certificaciones de Calidad de procesos y servicios administrativos' ]),
            new ArchivoSerie(['clave' => '15', 'nombre' => 'Desconcentración de funciones' ]),
            new ArchivoSerie(['clave' => '16', 'nombre' => 'Descentralización' ]),
            new ArchivoSerie(['clave' => '17', 'nombre' => 'Disposiciones en materia de presupuestación' ]),
            new ArchivoSerie(['clave' => '18', 'nombre' => 'Programas y proyectos en materia de presupuesto' ]),
            new ArchivoSerie(['clave' => '19', 'nombre' => 'Análisis financiero y presupuestal' ]),
            new ArchivoSerie(['clave' => '20', 'nombre' => 'Evaluación y control del ejercicio presupuestal' ]),

        ]);
        ArchivoSeccion::create([ 'clave' => '4C', 'nombre' => 'Recursos humanos'  ])->series()->saveMany([
            new ArchivoSerie(['clave' => '1', 'nombre' => 'Disposiciones en materia de recursos humanos' ]),
            new ArchivoSerie(['clave' => '2', 'nombre' => 'Programas y proyectos en materia de recursos humanos' ]),
            new ArchivoSerie(['clave' => '3', 'nombre' => 'Expediente único de personal' ]),
            new ArchivoSerie(['clave' => '4', 'nombre' => 'Registro y control de presupuestos y plazas' ]),
            new ArchivoSerie(['clave' => '5', 'nombre' => 'Nómina de pago de personal' ]),
            new ArchivoSerie(['clave' => '6', 'nombre' => 'Reclutamiento y selección de personal' ]),
            new ArchivoSerie(['clave' => '7', 'nombre' => 'Identificación y acreditación de personal' ]),
            new ArchivoSerie(['clave' => '8', 'nombre' => 'Control de asistencia (vacaciones, descansos, licencias, incapacidades, etc.)' ]),
            new ArchivoSerie(['clave' => '9', 'nombre' => 'Control disciplinario' ]),
            new ArchivoSerie(['clave' => '10', 'nombre' => 'Descuentos' ]),
            new ArchivoSerie(['clave' => '11', 'nombre' => 'Estímulos y recompensas' ]),
            new ArchivoSerie(['clave' => '12', 'nombre' => 'Evaluaciones y promociones' ]),
            new ArchivoSerie(['clave' => '13', 'nombre' => 'Productividad en el trabajo' ]),
            new ArchivoSerie(['clave' => '14', 'nombre' => 'Evaluación del desempeño de los servidores de mando' ]),
            new ArchivoSerie(['clave' => '15', 'nombre' => 'Filiaciones al ISSSTE' ]),
            new ArchivoSerie(['clave' => '16', 'nombre' => 'Control de prestaciones en materia económica (SAR, seguros, etc.)' ]),
            new ArchivoSerie(['clave' => '17', 'nombre' => 'Jubilaciones y pensiones' ]),
            new ArchivoSerie(['clave' => '18', 'nombre' => 'Programas de retiro voluntario' ]),
            new ArchivoSerie(['clave' => '19', 'nombre' => 'Becas' ]),
            new ArchivoSerie(['clave' => '20', 'nombre' => 'Relaciones laborales (Comisiones Mixtas, sindicato de trabajadores al servicio del Estado, condiciones laborales)' ]),
            new ArchivoSerie(['clave' => '21', 'nombre' => 'Servicios sociales, culturales, de seguridad e higiene en el trabajo.' ]),
            new ArchivoSerie(['clave' => '22', 'nombre' => 'Capacitación continua y desarrollo profesional del personal de áreas administrativas' ]),
            new ArchivoSerie(['clave' => '23', 'nombre' => 'Servicio social de áreas administrativas' ]),
            new ArchivoSerie(['clave' => '24', 'nombre' => 'Curricula de personal' ]),
            new ArchivoSerie(['clave' => '25', 'nombre' => 'Censo de personal' ]),
            new ArchivoSerie(['clave' => '26', 'nombre' => 'Expedición de constancias y credenciales' ]),
            new ArchivoSerie(['clave' => '27', 'nombre' => 'Coordinación laboral con organismos descentralizados y paraestatales' ]),
            new ArchivoSerie(['clave' => '28', 'nombre' => 'Servicio profesional de carrera' ]),


        ]);
        ArchivoSeccion::create([ 'clave' => '5C', 'nombre' => 'Recursos financieros'  ])->series()->saveMany([
            new ArchivoSerie(['clave' => '1', 'nombre' => 'Disposiciones en materia de recursos financieros' ]),
            new ArchivoSerie(['clave' => '2', 'nombre' => 'Programas y proyectos sobre recursos financieros y contabilidad' ]),
            new ArchivoSerie(['clave' => '3', 'nombre' => 'Gastos o egresos por partida presupuestal' ]),
            new ArchivoSerie(['clave' => '4', 'nombre' => 'Ingresos' ]),
            new ArchivoSerie(['clave' => '5', 'nombre' => 'Libros contables' ]),
            new ArchivoSerie(['clave' => '6', 'nombre' => 'Registros contables (glosa)' ]),
            new ArchivoSerie(['clave' => '7', 'nombre' => 'Valores financieros' ]),
            new ArchivoSerie(['clave' => '8', 'nombre' => 'Aportaciones a capital' ]),
            new ArchivoSerie(['clave' => '9', 'nombre' => 'Empréstitos' ]),
            new ArchivoSerie(['clave' => '10', 'nombre' => 'Financiamiento externo' ]),
            new ArchivoSerie(['clave' => '11', 'nombre' => 'Esquemas de financiamiento' ]),
            new ArchivoSerie(['clave' => '12', 'nombre' => 'Asignación y optimización de recursos financieros' ]),
            new ArchivoSerie(['clave' => '13', 'nombre' => 'Créditos concedidos' ]),
            new ArchivoSerie(['clave' => '14', 'nombre' => 'Cuentas por liquidar certificadas' ]),
            new ArchivoSerie(['clave' => '15', 'nombre' => 'Transferencias de presupuesto' ]),
            new ArchivoSerie(['clave' => '16', 'nombre' => 'Ampliaciones de presupuesto' ]),
            new ArchivoSerie(['clave' => '17', 'nombre' => 'Registro y control de pólizas de ingresos' ]),
            new ArchivoSerie(['clave' => '18', 'nombre' => 'Registro y control de pólizas de egresos' ]),
            new ArchivoSerie(['clave' => '19', 'nombre' => 'Pólizas de diario' ]),
            new ArchivoSerie(['clave' => '20', 'nombre' => 'Compras directas' ]),
            new ArchivoSerie(['clave' => '21', 'nombre' => 'Garantías, fianzas y depósitos' ]),
            new ArchivoSerie(['clave' => '22', 'nombre' => 'Control de cheques' ]),
            new ArchivoSerie(['clave' => '23', 'nombre' => 'Conciliaciones' ]),
            new ArchivoSerie(['clave' => '24', 'nombre' => 'Estados financieros' ]),
            new ArchivoSerie(['clave' => '25', 'nombre' => 'Auxiliares de cuentas' ]),
            new ArchivoSerie(['clave' => '26', 'nombre' => 'Estado del ejercicio de presupuesto' ]),
            new ArchivoSerie(['clave' => '27', 'nombre' => 'Fondo Rotatorio' ]),
            new ArchivoSerie(['clave' => '28', 'nombre' => 'Pago de derechos' ]),

        ]);
        ArchivoSeccion::create([ 'clave' => '6C', 'nombre' => 'Recursos materiales y obra pública'  ])->series()->saveMany([
            new ArchivoSerie(['clave' => '1', 'nombre' => 'Disposiciones en materia de recursos materiales, obra pública, conservación y mantenimiento' ]),
            new ArchivoSerie(['clave' => '2', 'nombre' => 'Programas y proyectos en materia de recursos materiales, obra pública, conservación y mantenimiento' ]),
            new ArchivoSerie(['clave' => '3', 'nombre' => 'Licitaciones' ]),
            new ArchivoSerie(['clave' => '4', 'nombre' => 'Adquisiciones' ]),
            new ArchivoSerie(['clave' => '5', 'nombre' => 'Sanciones, inconformidades y conciliaciones, derivados de contratos' ]),
            new ArchivoSerie(['clave' => '6', 'nombre' => 'Contratos' ]),
            new ArchivoSerie(['clave' => '7', 'nombre' => 'Seguros y fianzas' ]),
            new ArchivoSerie(['clave' => '8', 'nombre' => 'Suspensión, rescisión, terminación de obra pública' ]),
            new ArchivoSerie(['clave' => '9', 'nombre' => 'Bitácora de obra pública' ]),
            new ArchivoSerie(['clave' => '10', 'nombre' => 'Calidad en materia de obras, conservación y equipamiento' ]),
            new ArchivoSerie(['clave' => '11', 'nombre' => 'Precios unitarios en obra pública y servicios' ]),
            new ArchivoSerie(['clave' => '12', 'nombre' => 'Asesoría técnica en materia de obra pública' ]),
            new ArchivoSerie(['clave' => '13', 'nombre' => 'Conservación y mantenimiento de la infraestructura física' ]),
            new ArchivoSerie(['clave' => '14', 'nombre' => 'Registro de proveedores y contratistas' ]),
            new ArchivoSerie(['clave' => '15', 'nombre' => 'Arrendamientos' ]),
            new ArchivoSerie(['clave' => '16', 'nombre' => 'Disposiciones de activo fijo' ]),
            new ArchivoSerie(['clave' => '17', 'nombre' => 'Inventario físico y control de bienes muebles' ]),
            new ArchivoSerie(['clave' => '18', 'nombre' => 'Inventario físico y control de insumos' ]),
            new ArchivoSerie(['clave' => '19', 'nombre' => 'Almacenamiento, control y distribución de bienes muebles' ]),
            new ArchivoSerie(['clave' => '20', 'nombre' => 'Disposiciones y sistemas de abastecimiento y almacenes' ]),
            new ArchivoSerie(['clave' => '21', 'nombre' => 'Control de calidad de bienes e insumos' ]),
            new ArchivoSerie(['clave' => '22', 'nombre' => 'Control y seguimiento de obras y remodelaciones' ]),
            new ArchivoSerie(['clave' => '23', 'nombre' => 'Comités y subcomités de adquisiciones, arrendamientos y servicios' ]),
            new ArchivoSerie(['clave' => '24', 'nombre' => 'Comité de enajenación de bienes muebles e inmuebles' ]),
            new ArchivoSerie(['clave' => '25', 'nombre' => 'Comité de obra pública' ]),
            new ArchivoSerie(['clave' => '26', 'nombre' => 'Comisiones consultivas mixtas de abastecimiento' ]),
        ]);
        ArchivoSeccion::create([ 'clave' => '7C', 'nombre' => 'Servicios generales'  ])->series()->saveMany([
            new ArchivoSerie(['clave' => '1', 'nombre' => 'Disposiciones en materia de servicios generales' ]),
            new ArchivoSerie(['clave' => '2', 'nombre' => 'Programas y proyectos en servicios generales' ]),
            new ArchivoSerie(['clave' => '3', 'nombre' => 'Servicios básicos (energía eléctrica, agua, predial, etc.)' ]),
            new ArchivoSerie(['clave' => '4', 'nombre' => 'Servicios de embalaje fletes y maniobras' ]),
            new ArchivoSerie(['clave' => '5', 'nombre' => 'Servicios de seguridad y vigilancia' ]),
            new ArchivoSerie(['clave' => '6', 'nombre' => 'Servicios de lavandería, higiene y fumigación' ]),
            new ArchivoSerie(['clave' => '7', 'nombre' => 'Servicios de transportación' ]),
            new ArchivoSerie(['clave' => '8', 'nombre' => 'Servicios de telefonía, telefonía celular y radiolocalización' ]),
            new ArchivoSerie(['clave' => '9', 'nombre' => 'Servicio postal' ]),
            new ArchivoSerie(['clave' => '10', 'nombre' => 'Servicios especializados de mensajería' ]),
            new ArchivoSerie(['clave' => '11', 'nombre' => 'Mantenimiento, conservación e instalación de mobiliario' ]),
            new ArchivoSerie(['clave' => '12', 'nombre' => 'Mantenimiento, conservación e instalación de equipo de Cómputo' ]),
            new ArchivoSerie(['clave' => '13', 'nombre' => 'Control de parque vehicular' ]),
            new ArchivoSerie(['clave' => '14', 'nombre' => 'Vales de combustible' ]),
            new ArchivoSerie(['clave' => '15', 'nombre' => 'Control y servicios en auditorios y salas' ]),
            new ArchivoSerie(['clave' => '16', 'nombre' => 'Protección civil' ]),
        ]);
        ArchivoSeccion::create([ 'clave' => '8C', 'nombre' => 'Tecnologías y servicios de la información'  ])->series()->saveMany([
            new ArchivoSerie(['clave' => '1', 'nombre' => 'Disposiciones en materia de telecomunicaciones' ]),
            new ArchivoSerie(['clave' => '2', 'nombre' => 'Programas y proyectos en materia de telecomunicaciones' ]),
            new ArchivoSerie(['clave' => '3', 'nombre' => 'Normatividad tecnológica' ]),
            new ArchivoSerie(['clave' => '4', 'nombre' => 'Desarrollo e infraestructura de telecomunicaciones' ]),
            new ArchivoSerie(['clave' => '5', 'nombre' => 'Desarrollo e infraestructura del portal de Internet de la dependencia' ]),
            new ArchivoSerie(['clave' => '6', 'nombre' => 'Desarrollo de redes comunicativas de voz y datos' ]),
            new ArchivoSerie(['clave' => '7', 'nombre' => 'Disposiciones en materia de informática' ]),
            new ArchivoSerie(['clave' => '8', 'nombre' => 'Programas y proyectos sobre informática' ]),
            new ArchivoSerie(['clave' => '9', 'nombre' => 'Desarrollo informático' ]),
            new ArchivoSerie(['clave' => '10', 'nombre' => 'Seguridad informática' ]),
            new ArchivoSerie(['clave' => '11', 'nombre' => 'Desarrollo de sistemas' ]),
            new ArchivoSerie(['clave' => '12', 'nombre' => 'Automatización de procesos' ]),
            new ArchivoSerie(['clave' => '13', 'nombre' => 'Control y desarrollo del parque informático' ]),
            new ArchivoSerie(['clave' => '14', 'nombre' => 'Disposiciones en materia de servicios de información' ]),
            new ArchivoSerie(['clave' => '15', 'nombre' => 'Programas y proyectos en materia de servicios de información' ]),
            new ArchivoSerie(['clave' => '16', 'nombre' => 'Administración y servicios de archivo' ]),
            new ArchivoSerie(['clave' => '17', 'nombre' => 'Administración y servicios de correspondencia' ]),
            new ArchivoSerie(['clave' => '18', 'nombre' => 'Administración y servicios de bibliotecas' ]),
            new ArchivoSerie(['clave' => '19', 'nombre' => 'Administración y servicios de otros centros documentales' ]),
            new ArchivoSerie(['clave' => '20', 'nombre' => 'Administración y presentación de acervos digitales' ]),
            new ArchivoSerie(['clave' => '21', 'nombre' => 'Instrumentos de consulta y control de archivos' ]),
            new ArchivoSerie(['clave' => '22', 'nombre' => 'Procesos técnicos en los servicios de información' ]),
            new ArchivoSerie(['clave' => '23', 'nombre' => 'Acceso y reservas en servicios de información' ]),
            new ArchivoSerie(['clave' => '24', 'nombre' => 'Productos para la divulgación de servicios' ]),
            new ArchivoSerie(['clave' => '25', 'nombre' => 'Servicios y productos en Internet e intranet' ]),
        ]);
        ArchivoSeccion::create([ 'clave' => '9C', 'nombre' => 'Comunicación social'  ])->series()->saveMany([
            new ArchivoSerie(['clave' => '1', 'nombre' => 'Disposiciones en materia de comunicación social y relaciones públicas' ]),
            new ArchivoSerie(['clave' => '2', 'nombre' => 'Programas y proyectos de comunicación social' ]),
            new ArchivoSerie(['clave' => '3', 'nombre' => 'Publicaciones e impresos institucionales' ]),
            new ArchivoSerie(['clave' => '4', 'nombre' => 'Materia multimedia' ]),
            new ArchivoSerie(['clave' => '5', 'nombre' => 'Publicidad institucional' ]),
            new ArchivoSerie(['clave' => '6', 'nombre' => 'Boletines y entrevistas para medios' ]),
            new ArchivoSerie(['clave' => '7', 'nombre' => 'Boletines informativos para medios' ]),
            new ArchivoSerie(['clave' => '8', 'nombre' => 'Inserciones y anuncios en periódicos y revistas' ]),
            new ArchivoSerie(['clave' => '9', 'nombre' => 'Agencias periodísticas, de noticias, reporteros, articulistas, cadenas televisivas y otros medios de comunicación social' ]),
            new ArchivoSerie(['clave' => '10', 'nombre' => 'Notas para medios' ]),
            new ArchivoSerie(['clave' => '11', 'nombre' => 'Prensa institucional' ]),
            new ArchivoSerie(['clave' => '12', 'nombre' => 'Disposiciones en materia de relaciones públicas' ]),
            new ArchivoSerie(['clave' => '13', 'nombre' => 'Comparecencias ante el poder legislativo' ]),
            new ArchivoSerie(['clave' => '14', 'nombre' => 'Actos y eventos oficiales' ]),
            new ArchivoSerie(['clave' => '15', 'nombre' => 'Registro de audiencias públicas' ]),
            new ArchivoSerie(['clave' => '16', 'nombre' => 'Invitaciones y felicitaciones' ]),
            new ArchivoSerie(['clave' => '17', 'nombre' => 'Servicios de edecanes' ]),
            new ArchivoSerie(['clave' => '18', 'nombre' => 'Encuestas de opinión' ]),
        ]);
        ArchivoSeccion::create([ 'clave' => '10C', 'nombre' => 'Control y auditoria de actividades públicas'  ])->series()->saveMany([
            new ArchivoSerie(['clave' => '1', 'nombre' => 'Disposiciones en materia de control y auditoria' ]),
            new ArchivoSerie(['clave' => '2', 'nombre' => 'Programas y proyectos en materia de control y auditoria' ]),
            new ArchivoSerie(['clave' => '3', 'nombre' => 'Auditoria' ]),
            new ArchivoSerie(['clave' => '4', 'nombre' => 'Visitadurías' ]),
            new ArchivoSerie(['clave' => '5', 'nombre' => 'Revisiones de rubros específicos' ]),
            new ArchivoSerie(['clave' => '6', 'nombre' => 'Seguimiento a la aplicación en medidas o recomendaciones' ]),
            new ArchivoSerie(['clave' => '7', 'nombre' => 'Participantes en comités' ]),
            new ArchivoSerie(['clave' => '8', 'nombre' => 'Requerimientos de información a dependencias y entidades' ]),
            new ArchivoSerie(['clave' => '9', 'nombre' => 'Quejas y denuncias de actividades públicas' ]),
            new ArchivoSerie(['clave' => '10', 'nombre' => 'Peticiones, sugerencias y recomendaciones' ]),
            new ArchivoSerie(['clave' => '11', 'nombre' => 'Responsabilidades' ]),
            new ArchivoSerie(['clave' => '12', 'nombre' => 'Inconformidades' ]),
            new ArchivoSerie(['clave' => '13', 'nombre' => 'Inhabilitaciones' ]),
            new ArchivoSerie(['clave' => '14', 'nombre' => 'Declaraciones patrimoniales' ]),
            new ArchivoSerie(['clave' => '15', 'nombre' => 'Actas de entrega a recepción' ]),
            new ArchivoSerie(['clave' => '16', 'nombre' => 'Libros blancos' ]),
        ]);
        ArchivoSeccion::create([ 'clave' => '11C', 'nombre' => 'Planeación, información, evaluación y políticas'  ])->series()->saveMany([
            new ArchivoSerie(['clave' => '1', 'nombre' => 'Disposiciones en materia de información y evaluación' ]),
            new ArchivoSerie(['clave' => '2', 'nombre' => 'Disposiciones en materia de planeación' ]),
            new ArchivoSerie(['clave' => '3', 'nombre' => 'Disposiciones en materia de políticas' ]),
            new ArchivoSerie(['clave' => '4', 'nombre' => 'Programas y proyectos de información y evaluación' ]),
            new ArchivoSerie(['clave' => '5', 'nombre' => 'Programas y proyectos sobre política' ]),
            new ArchivoSerie(['clave' => '6', 'nombre' => 'Planes estatales' ]),
            new ArchivoSerie(['clave' => '7', 'nombre' => 'Programas a mediano plazo' ]),
            new ArchivoSerie(['clave' => '8', 'nombre' => 'Programas de acción' ]),
            new ArchivoSerie(['clave' => '9', 'nombre' => 'Sistemas de información estadística de la dependencia' ]),
            new ArchivoSerie(['clave' => '10', 'nombre' => 'Normas de elaboración y actualización de la información estadística' ]),
            new ArchivoSerie(['clave' => '11', 'nombre' => 'Captación, producción y difusión de la información estadística' ]),
            new ArchivoSerie(['clave' => '12', 'nombre' => 'Desarrollo de encuestas' ]),
            new ArchivoSerie(['clave' => '13', 'nombre' => 'Evaluación de programas de acción' ]),
            new ArchivoSerie(['clave' => '14', 'nombre' => 'Informes mensuales y anuales de labores' ]),
            new ArchivoSerie(['clave' => '15', 'nombre' => 'Informe de ejecución' ]),
            new ArchivoSerie(['clave' => '16', 'nombre' => 'Informe de gobierno' ]),
            new ArchivoSerie(['clave' => '17', 'nombre' => 'Indicadores' ]),
            new ArchivoSerie(['clave' => '18', 'nombre' => 'Indicadores de desempeño, calidad y productividad' ]),
            new ArchivoSerie(['clave' => '19', 'nombre' => 'Normas para la evaluación' ]),
            new ArchivoSerie(['clave' => '20', 'nombre' => 'Modelos de organización' ]),
        ]);
        ArchivoSeccion::create([ 'clave' => '12C', 'nombre' => 'Transparencia y acceso a la información'  ])->series()->saveMany([
            new ArchivoSerie(['clave' => '1', 'nombre' => 'Disposiciones en materia de acceso a la información' ]),
            new ArchivoSerie(['clave' => '2', 'nombre' => 'Programas y proyectos de acceso a la información' ]),
            new ArchivoSerie(['clave' => '3', 'nombre' => 'Programas y proyectos en materia de transparencia y combate a la corrupción' ]),
            new ArchivoSerie(['clave' => '4', 'nombre' => 'Unidades de enlace' ]),
            new ArchivoSerie(['clave' => '5', 'nombre' => 'Comité de información' ]),
            new ArchivoSerie(['clave' => '6', 'nombre' => 'Solicitudes de acceso a la información' ]),
            new ArchivoSerie(['clave' => '7', 'nombre' => 'Portal de transparencia' ]),
            new ArchivoSerie(['clave' => '8', 'nombre' => 'Clasificación de información reservada' ]),
            new ArchivoSerie(['clave' => '9', 'nombre' => 'Clasificación de información confidencial' ]),
            new ArchivoSerie(['clave' => '10', 'nombre' => 'Sistemas de datos personales' ]),
            new ArchivoSerie(['clave' => '11', 'nombre' => 'Instituto estatal de acceso a la información' ]),

        ]);

    }
}
