<script type="text/javascript" src="{{ asset('vendor/jq/jqxcore.js') }}"></script>
<script type="text/javascript" src="{{ asset('vendor/jq/jqxdata.js') }}"></script>
<script type="text/javascript" src="{{ asset('vendor/jq/jqxbuttons.js') }}"></script>
<script type="text/javascript" src="{{ asset('vendor/jq/jqxscrollbar.js') }}"></script>
<script type="text/javascript" src="{{ asset('vendor/jq/jqxlistbox.js') }}"></script>
<script type="text/javascript" src="{{ asset('vendor/jq/jqxdropdownlist.js') }}"></script>
<script type="text/javascript" src="{{ asset('vendor/jq/jqxmenu.js') }}"></script>
<script type="text/javascript" src="{{ asset('vendor/jq/jqxinput.js') }}"></script>
<script type="text/javascript" src="{{ asset('vendor/jq/jqxgrid.js') }}"></script>
<script type="text/javascript" src="{{ asset('vendor/jq/jqxgrid.pager.js') }}"></script>
<script type="text/javascript" src="{{ asset('vendor/jq/jqxgrid.filter.js') }}"></script>
<script type="text/javascript" src="{{ asset('vendor/jq/jqxgrid.sort.js') }}"></script>
<script type="text/javascript" src="{{ asset('vendor/jq/jqxgrid.storage.js') }}"></script>
<script type="text/javascript" src="{{ asset('vendor/jq/jqxgrid.columnsresize.js') }}"></script>
<script type="text/javascript" src="{{ asset('vendor/jq/jqxgrid.columnsreorder.js') }}"></script>
<script type="text/javascript" src="{{ asset('vendor/jq/jqxgrid.selection.js') }}"></script>
<script type="text/javascript" src="{{ asset('vendor/jq/jqxpanel.js') }}"></script>
<script type="text/javascript" src="{{ asset('vendor/jq/jqxcalendar.js') }}"></script>
<script type="text/javascript" src="{{ asset('vendor/jq/jqxdatetimeinput.js') }}"></script>
<script type="text/javascript" src="{{ asset('vendor/jq/jqxcheckbox.js') }}"></script>
<script type="text/javascript" src="{{ asset('vendor/jq/es.js') }}"></script>
<script type="text/javascript" src="{{ asset('vendor/jq/jqxdata.export.js') }}"></script>
<script type="text/javascript" src="{{ asset('vendor/jq/jqxgrid.export.js') }}"></script>
<script type="text/javascript" src="{{ asset('vendor/jq/jqxexport.js') }}"></script>
<script type="text/javascript" src="{{ asset('vendor/jszip/jszip.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('vendor/select2/select2.full.js') }}"></script>
<script type="text/javascript" src="{{ asset('vendor/select2/es.js') }}"></script>
